spring:
  application:
    name: spring-boot-mongo-demo
  data:
    mongodb:
      uri: mongodb+srv://root:root@mongodemo.cofulvq.mongodb.net/?retryWrites=true&w=majority&appName=mongoDemo
      database: person-demo-db

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
springdoc:
  api-docs:
    path: /api-docs